# fly.toml app configuration file generated for fso-part3-telephonebook on 2023-11-25T21:13:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-part3-telephonebook"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
